# Generated by Django 5.0.6 on 2024-05-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file',
            field=models.FileField(default='audio_files/default.mp3', upload_to='audio_files/'),
        ),
    ]
