# Generated by Django 5.0.6 on 2024-06-15 20:32

import audio_analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='audio_files/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.CharField(choices=[(audio_analysis.models.Sentiment['POSITIVE'], 'positive'), (audio_analysis.models.Sentiment['NEGATIVE'], 'negative'), (audio_analysis.models.Sentiment['NEUTRAL'], 'neutral')], max_length=255)),
                ('confidence_score', models.FloatField()),
                ('analysis_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='audio_file',
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
    ]
