# Generated by Django 5.0.6 on 2024-05-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_analysis', '0002_audiofile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='file_url',
        ),
    ]
