# Generated by Django 5.0.6 on 2024-06-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_analysis', '0002_audioanalysis_remove_sentimentanalysis_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioanalysis',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=10),
        ),
    ]
