# Generated by Django 5.0.6 on 2024-05-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_analysis', '0003_remove_audiofile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to='audio_files/'),
        ),
    ]
