# Generated by Django 5.0.6 on 2024-05-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bio_customuser_photo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contribution', models.TextField(help_text='Detailed description of the contributions made by the individual.')),
                ('title', models.CharField(blank=True, help_text='Professional title of the contributor.', max_length=255)),
                ('area_of_expertise', models.CharField(blank=True, help_text='Area of expertise of the contributor.', max_length=255)),
                ('personal_website', models.URLField(blank=True, help_text='Personal or professional website URL.', null=True)),
                ('linkedin_profile', models.URLField(blank=True, help_text='LinkedIn profile URL.', null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address.', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
